# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroningerAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='time_stamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
